springdoc:
  api-docs:
    path: /v3/api-docs   # Path for OpenAPI documentation
  swagger-ui:
    path: /swagger-ui.html   # Path for Swagger UI

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/School?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
