springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:mysql://production-db:3306/School?allowPublicKeyRetrieval=true&useSSL=false
    username: prod-user
    password: prod-password
  jpa:
    hibernate:
      ddl-auto: validate  # In production, you should not use 'update'
    show-sql: false       # Disable SQL logging in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080